NAME = philo

FSANITIZE = -g3 -fsanitize=address

SRCSPATH = srcs

HEADERS = includes \

SRCS =  
		
CC = gcc

CFLAGS = -MMD -Wall -Werror -Wextra $(FSANITIZE)

RM = rm -rf

OBJS =  $(addprefix $(OBJ_PATH)/,$(SRCS:.c=.o))

DEPS = $(OBJS:.o=.d)

vpath %.h $(HEADERS)
vpath %.c $(SRCSPATH)
vpath %.o $(OBJ_PATH)

all: $(NAME)

$(NAME):	$(OBJS)
			$(CC) $(CFLAGS) $(OBJS) -I $(HEADERS) -o $(NAME)

$(OBJ_PATH)/%.o:		%.c
			$(CC) $(CFLAGS) -I $(HEADERS) -c $< -o $@

$(OBJS):	| $(OBJ_PATH)

$(OBJ_PATH):
			mkdir -p $(OBJ_PATH)

clean:
		${RM} $(OBJ_PATH)

fclean:
		make clean
		${RM} ${NAME}

re:
	make fclean
	make all

-include $(DEPS)

.PHONY:			all clean fclean re